//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITgeek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itgeekEntities3 : DbContext
    {
        public itgeekEntities3()
            : base("name=itgeekEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategoria> kategoria { get; set; }
        public virtual DbSet<komentarz> komentarz { get; set; }
        public virtual DbSet<ocena_komentarza> ocena_komentarza { get; set; }
        public virtual DbSet<ocena_podkomentarza> ocena_podkomentarza { get; set; }
        public virtual DbSet<ocena_projektu> ocena_projektu { get; set; }
        public virtual DbSet<pliki> pliki { get; set; }
        public virtual DbSet<podkomentarz> podkomentarz { get; set; }
        public virtual DbSet<pozycja_kategorii> pozycja_kategorii { get; set; }
        public virtual DbSet<projekt> projekt { get; set; }
        public virtual DbSet<uzytkownik> uzytkownik { get; set; }
        public virtual DbSet<wideo> wideo { get; set; }
        public virtual DbSet<zdjecia> zdjecia { get; set; }
    }
}
