//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITgeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class komentarz
    {
        public komentarz()
        {
            this.ocena_komentarza = new HashSet<ocena_komentarza>();
            this.podkomentarz = new HashSet<podkomentarz>();
        }
    
        public int id_komentarz { get; set; }
        public int id_uzytkownik { get; set; }
        public string tresc_komentarza { get; set; }
        public Nullable<int> id_projekt { get; set; }
    
        public virtual projekt projekt { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
        public virtual ICollection<ocena_komentarza> ocena_komentarza { get; set; }
        public virtual ICollection<podkomentarz> podkomentarz { get; set; }
    }
}
