//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITgeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocena_komentarza
    {
        public int id_ocena_komentarza { get; set; }
        public int id_komentarz { get; set; }
        public int id_uzytkownik { get; set; }
        public int ocena_komentarza1 { get; set; }
    
        public virtual komentarz komentarz { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
