
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ITgeek
{

using System;
    using System.Collections.Generic;
    
public partial class ocena_podkomentarza
{

    public int id_ocena_podkomentarza { get; set; }

    public int id_podkomentarz { get; set; }

    public int id_uzytkownik { get; set; }

    public int ocena_podkomentarza1 { get; set; }



    public virtual podkomentarz podkomentarz { get; set; }

    public virtual uzytkownik uzytkownik { get; set; }

}

}
