//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITgeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownik
    {
        public uzytkownik()
        {
            this.komentarz = new HashSet<komentarz>();
            this.ocena_komentarza = new HashSet<ocena_komentarza>();
            this.ocena_podkomentarza = new HashSet<ocena_podkomentarza>();
            this.ocena_projektu = new HashSet<ocena_projektu>();
            this.podkomentarz = new HashSet<podkomentarz>();
            this.projekt = new HashSet<projekt>();
        }
    
        public int id_uzytkownik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
        public string miejscowosc { get; set; }
        public string wyswietlana_nazwa { get; set; }
        public string email { get; set; }
        public string haslo { get; set; }
        public Nullable<int> uprawnienia { get; set; }
    
        public virtual ICollection<komentarz> komentarz { get; set; }
        public virtual ICollection<ocena_komentarza> ocena_komentarza { get; set; }
        public virtual ICollection<ocena_podkomentarza> ocena_podkomentarza { get; set; }
        public virtual ICollection<ocena_projektu> ocena_projektu { get; set; }
        public virtual ICollection<podkomentarz> podkomentarz { get; set; }
        public virtual ICollection<projekt> projekt { get; set; }
    }
}
