//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITgeek
{
    using System;
    using System.Collections.Generic;
    
    public partial class zdjecia
    {
        public int id_zdjecia { get; set; }
        public int id_projekt { get; set; }
        public string nazwa_zdjecia { get; set; }
        public byte[] Zdjecie { get; set; }
    
        public virtual projekt projekt { get; set; }
    }
}
